// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'sensor_data_dto.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6244136084561409203),
      name: 'SensorDataDTO',
      lastPropertyId: const IdUid(6, 2292311947347465684),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6405584338984999105),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5683084747828511117),
            name: 'data',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 728111890858328048),
            name: 'maxPrecision',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7805252819587513877),
            name: 'sensorID',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4945270714076906575),
            name: 'dateTime',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2292311947347465684),
            name: 'unit',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 6244136084561409203),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    SensorDataDTO: EntityDefinition<SensorDataDTO>(
        model: _entities[0],
        toOneRelations: (SensorDataDTO object) => [],
        toManyRelations: (SensorDataDTO object) => {},
        getId: (SensorDataDTO object) => object.id,
        setId: (SensorDataDTO object, int id) {
          object.id = id;
        },
        objectToFB: (SensorDataDTO object, fb.Builder fbb) {
          final dataOffset = fbb.writeString(object.data);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, dataOffset);
          fbb.addInt64(2, object.maxPrecision);
          fbb.addInt64(3, object.sensorID);
          fbb.addInt64(4, object.dateTime.millisecondsSinceEpoch);
          fbb.addInt64(5, object.unit);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = SensorDataDTO()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..data = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..maxPrecision =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..sensorID =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..dateTime = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0))
            ..unit =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [SensorDataDTO] entity fields to define ObjectBox queries.
class SensorDataDTO_ {
  /// see [SensorDataDTO.id]
  static final id =
      QueryIntegerProperty<SensorDataDTO>(_entities[0].properties[0]);

  /// see [SensorDataDTO.data]
  static final data =
      QueryStringProperty<SensorDataDTO>(_entities[0].properties[1]);

  /// see [SensorDataDTO.maxPrecision]
  static final maxPrecision =
      QueryIntegerProperty<SensorDataDTO>(_entities[0].properties[2]);

  /// see [SensorDataDTO.sensorID]
  static final sensorID =
      QueryIntegerProperty<SensorDataDTO>(_entities[0].properties[3]);

  /// see [SensorDataDTO.dateTime]
  static final dateTime =
      QueryIntegerProperty<SensorDataDTO>(_entities[0].properties[4]);

  /// see [SensorDataDTO.unit]
  static final unit =
      QueryIntegerProperty<SensorDataDTO>(_entities[0].properties[5]);
}
